# .github/workflows/security.yaml (veya build-and-sbom.yaml)

name: SAST Scan, Build, and SBOM Generation

on:
  push:
    branches: [ main ] # Veya kendi ana branch'inizin adı
  workflow_dispatch:

jobs:
  security_pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Depodaki kodu (Dockerfile dahil) al
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------- SAST Taraması (Başa Alındı) --------------------
      # 2. Adım: Semgrep SAST Taramasını Çalıştır
      - name: Run Semgrep SAST Scan
        uses: semgrep/semgrep-action@v1
        id: semgrep
        with:
          # === DEĞİŞİKLİK BURADA ===
          # 'generate_sarif' kaldırıldı.
          # Kurallar 'config' ile belirtildi.
          # SARIF çıktısı için gerekli argümanlar 'args' ile eklendi.
          config: "p/default" # Kullanılacak kural seti (örn: varsayılanlar)
          args: "--sarif -o semgrep.sarif" # Semgrep CLI'a iletilecek argümanlar

      # 3. Adım (Hata Ayıklama İçin): Dosyaları Listele
      - name: List files after Semgrep
        run: ls -la
        if: always() # Sorun çözüldüğünde bu adım kaldırılabilir.

      # 4. Adım: Semgrep SARIF Sonuçlarını Yükle (GitHub Security Tab için)
      - name: Upload Semgrep SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif # Şimdi bu dosyanın oluşturulmuş olması lazım
      # -------------------- SAST Taraması Bitti ---------------------------

      # 5. Adım: Docker Buildx'i kur
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Adım: Docker imajını build et
      # ... (geri kalan adımlar aynı) ...
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: juice-shop-local:latest

      # 7. Adım: Syft SBOM aracını kur
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      # 8. Adım: SBOM oluştur (SPDX ve CycloneDX formatlarında)
      - name: Generate SBOM from Docker image
        run: |
          syft packages docker:juice-shop-local:latest -o spdx-json=sbom-spdx.json
          syft packages docker:juice-shop-local:latest -o cyclonedx-json=sbom-cyclonedx.json

      # 9. Adım: Oluşturulan SBOM dosyalarını artifact olarak kaydet
      - name: Upload SBOM artifact (SPDX)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom-spdx.json

      - name: Upload SBOM artifact (CycloneDX)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom-cyclonedx.json
