# .github/workflows/security.yaml (veya build-and-sbom.yaml)

name: Build, SBOM, and SAST Scan

on:
  push:
    branches: [ main ] # Veya kendi ana branch'inizin adı
  workflow_dispatch:

jobs:
  security_pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Depodaki kodu (Dockerfile dahil) al
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Adım: Docker Buildx'i kur (modern build için)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Adım: Docker imajını build et
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: juice-shop-local:latest

      # 4. Adım: Syft SBOM aracını kur
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      # 5. Adım: SBOM oluştur (SPDX ve CycloneDX formatlarında)
      - name: Generate SBOM from Docker image
        run: |
          syft packages docker:juice-shop-local:latest -o spdx-json=sbom-spdx.json
          syft packages docker:juice-shop-local:latest -o cyclonedx-json=sbom-cyclonedx.json

      # 6. Adım: Oluşturulan SBOM dosyalarını artifact olarak kaydet
      - name: Upload SBOM artifact (SPDX)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom-spdx.json

      - name: Upload SBOM artifact (CycloneDX)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom-cyclonedx.json

      # -------------------- SAST Taraması (Sona Alındı) --------------------
      # 7. Adım: Semgrep SAST Taramasını Çalıştır
      # Kaynak kodu tarar (Build veya SBOM sonucunu değil!)
      - name: Run Semgrep SAST Scan
        uses: semgrep/semgrep-action@v1
        id: semgrep # Sonraki adımlarda referans vermek için id ekleyebiliriz (opsiyonel)
        with:
          generate_sarif: "true"

      # 8. Adım: Semgrep SARIF Sonuçlarını Yükle
      # Sadece önceki Semgrep adımı başarılı olursa çalışır.
      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        # if: always() # <= KALDIRILDI! Şimdi sadece Semgrep başarılı olursa çalışacak.
        with:
          sarif_file: semgrep.sarif
      # -------------------- SAST Taraması Bitti ---------------------------
